### ISSUE TITLE
qutebrowser wayland webengine

### ISSUE THREAD

**Issue by enrico20026** [rsteube/qutebrowser-git#1]
https://forum.manjaro.org/t/qutebrowser-crash-without-qt5-wayland-deps/90727

**Comment by rsteube** [comment]
Hi, this was just a temporary fork from when the brave adblock engine wasn't yet merged.
You should report this [here](https://aur.archlinux.org/packages/qutebrowser-git/) on aur.
Alternatively opening an issue on [quitebrowser/qutebrowser](https://github.com/qutebrowser/qutebrowser) should also be fine since the package is maintained by @The-Compiler.

**Comment by The-Compiler** [comment]
Nope, qutebrowser doesn't need qt5-wayland to work. Maybe it does (like all Qt applications!) if you run it on Wayland without XWayland, but that's not really specific to qutebrowser.
